
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import NW, Menu, Scrollbar, Tk, Canvas, Entry, Text, Button, PhotoImage
from PIL import Image, ImageTk

from ListaDobleLigada.ListaD import ListaD
from ListaLigada.ListaS import ListaS
from ListaContigua import ListaContigua
from ListaIndexada import ListaIndexada

Doble = ListaD()
Simple = ListaS()
Contigua = ListaContigua()
Indexada = ListaIndexada()

L = 0

ruta = r"C:\Users\estef\OneDrive\Escritorio\UNIVERSIDAD\MIA\MIA_Practica1_202300547\Lista.png"
imagenCanva = None

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\estef\OneDrive\Escritorio\UNIVERSIDAD\MIA\MIA_Practica1_202300547\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("657x440")
window.configure(bg = "#BF2604")

def esconder():
    canvas.itemconfig(text_id, state='hidden')
    canvas.itemconfig(entry_bg_1, state='hidden')
    button_5.place_forget()
    button_6.place_forget()
    entry_1.place_forget()

def ocultarGrafica():
    global imagenCanva
    if imagenCanva is not None:
        canvas.delete(imagenCanva) 
        imagenCanva = None

def mostrarGrafica():
    global imagentk, imagenCanva
    ocultarGrafica()  
    try:
        imagen = Image.open(ruta)  
        imagentk = ImageTk.PhotoImage(imagen) 
        imagenCanva = canvas.create_image(416, 251, anchor="center", image=imagentk) 
    except Exception as e:
        print(f"Error al cargar la imagen: {e}")

#__________________________________________________________________
canvas = Canvas(
    window,
    bg = "#BF2604",
    height = 440,
    width = 657,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    328.0,
    220.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    328.0,
    34.0,
    image=image_image_2
)
#_______________________________________ligada simple______________________________________
def eliminarS():
    global L
    L = 1
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_5.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('eliminar S')

def agregarS():
    global L
    L = 1
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_6.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('agregar S')

def mostrarS():
    ocultarGrafica()
    Simple.graficar()
    mostrarGrafica()
    print('mostrar S')

menuListaS = Menu(window, tearoff=0)
menuListaS.add_command(label='Eliminar elemento', command=eliminarS)
menuListaS.add_command(label='Crear elemento', command=agregarS)
menuListaS.add_command(label='Mostrar Lista', command=mostrarS)

def mostrarmenuListaS(event):
    esconder()
    ocultarGrafica()
    entry_2.config(state="normal")
    entry_2.delete(0, "end")
    entry_2.insert(0, "Ligada Simple")
    entry_2.config(state="readonly")
    menuListaS.post(event.x_root, event.y_root)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=172.0,
    y=9.0,
    width=146.0,
    height=42.0
)
button_1.bind("<Button-1>", mostrarmenuListaS)

#_____________________________________doblemente ligada__________________________________
def eliminarLD():
    global L
    L = 2
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_5.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('eliminar LD')

def agregarLD():
    global L
    L = 2
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_6.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('agregar LD')

def mostrarLD():
    ocultarGrafica()
    Doble.graficar()
    mostrarGrafica()
    print('mostrar LD')

menuListaDL = Menu(window, tearoff=0)
menuListaDL.add_command(label='Eliminar elemento', command=eliminarLD)
menuListaDL.add_command(label='Crear elemento', command=agregarLD)
menuListaDL.add_command(label='Mostrar Lista', command=mostrarLD)

def mostrarmenuListaDL(event):
    esconder()
    ocultarGrafica()
    entry_2.config(state="normal")
    entry_2.delete(0, "end")
    entry_2.insert(0, "Doblemente Ligada")
    entry_2.config(state="readonly")
    menuListaDL.post(event.x_root, event.y_root)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=10.0,
    y=9.0,
    width=146.0,
    height=42.0
)
button_2.bind("<Button-1>", mostrarmenuListaDL)

#_______________________________________ligada indexada______________________________________
def eliminarI():
    global L
    L = 3
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_5.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('eliminar I')

def agregarI():
    global L
    L = 3
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_6.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('agregar I')

def mostrarI():
    ocultarGrafica()
    Indexada.graficar()
    mostrarGrafica()
    print('mostrar I')

menuListaI = Menu(window, tearoff=0)
menuListaI.add_command(label='Eliminar elemento', command=eliminarI)
menuListaI.add_command(label='Crear elemento', command=agregarI)
menuListaI.add_command(label='Mostrar Lista', command=mostrarI)

def mostrarmenuListaI(event):
    esconder()
    ocultarGrafica()
    entry_2.config(state="normal")
    entry_2.delete(0, "end")
    entry_2.insert(0, "Lista Indexada")
    entry_2.config(state="readonly")
    menuListaI.post(event.x_root, event.y_root)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=334.0,
    y=9.0,
    width=146.0,
    height=42.0
)
button_3.bind("<Button-1>", mostrarmenuListaI)

#_______________________________________ligada contigua______________________________________
def eliminarC():
    global L
    L = 4
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_5.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('eliminar C')

def agregarC():
    global L
    L = 4
    ocultarGrafica()
    canvas.itemconfig(text_id, state='normal')
    canvas.itemconfigure(entry_bg_1, state='normal')
    entry_1.place(x=24.5, y=190.0, width=136.0, height=21.0)
    button_6.place(x=27.0, y=232.0, width=125.0, height=45.0)
    print('agregar C')

def mostrarC():
    ocultarGrafica()
    Contigua.graficar()
    mostrarGrafica()
    print('mostrar C')

menuListaC = Menu(window, tearoff=0)
menuListaC.add_command(label='Eliminar elemento', command=eliminarC)
menuListaC.add_command(label='Crear elemento', command=agregarC)
menuListaC.add_command(label='Mostrar Lista', command=mostrarC)

def mostrarmenuListaC(event):
    esconder()
    ocultarGrafica()
    entry_2.config(state="normal")
    entry_2.delete(0, "end")
    entry_2.insert(0, "lista contigua")
    entry_2.config(state="readonly")
    menuListaC.post(event.x_root, event.y_root)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=496.0,
    y=9.0,
    width=146.0,
    height=42.0
)
button_4.bind("<Button-1>", mostrarmenuListaC)
#___________________________________________________________________
image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    416.0,
    251.0,
    image=image_image_3
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    92.5,
    201.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#F2F2F2",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=24.5,
    y=190.0,
    width=136.0,
    height=21.0
)

text_id = canvas.create_text(
    40.0,
    160.0,
    anchor="nw",
    text="ingrese el dato: ",
    fill="#FFFFFF",
    font=("HindGuntur Regular", 16 * -1)
)


image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    95.0,
    108.0,
    image=image_image_4
)

#_____________________________eliminar_________________________________
def eliminarElemento():
    dato = entry_1.get()
    #print(dato)
    #print(L)
    if L == 1:
        print('-'*5)
        Simple.eliminar(dato)
        Simple.imprimir()
    elif L == 2:
        print('-'*5)
        Doble.eliminar(dato)
        Doble.imprimir()
    elif L == 3:
        print('-'*5)
        Indexada.eliminar(dato)
        Indexada.imprimir()
    elif L == 4:
        print('-'*5)
        Contigua.eliminar(dato)
        Contigua.imprimir()

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command= eliminarElemento,
    relief="flat"
)
button_5.place(
    x=27.0,
    y=232.0,
    width=125.0,
    height=45.0
)

#______________________________________agregar______________________________________
def agregarElemento():
    dato = entry_1.get()
    #print(dato)
    #print(L)
    if L == 1:
        print('-'*5)
        Simple.insertar(dato)
        Simple.imprimir()
    elif L == 2:
        print('-'*5)
        Doble.insertar(dato)
        Doble.imprimir()
    elif L == 3:
        print('-'*5)
        Indexada.insertar(dato)
        Indexada.imprimir()
    elif L == 4:
        print('-'*5)
        Contigua.insertar(dato)
        Contigua.imprimir()

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=agregarElemento,
    relief="flat"
)
button_6.place(
    x=27.0,
    y=296.0,
    width=125.0,
    height=45.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    94.5,
    107.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#F2F2F2",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=26.5,
    y=96.0,
    width=136.0,
    height=21.0
)

canvas.itemconfig(text_id, state='hidden')
canvas.itemconfig(entry_bg_1, state='hidden')
button_5.place_forget()
button_6.place_forget()
entry_1.place_forget()

window.resizable(False, False)
window.mainloop()
